// <auto-generated />
using ManLab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ManLab.Migrations
{
    [DbContext(typeof(ManLabDataContext))]
    [Migration("20200119153526_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ManLab.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Name = "Tetap"
                        },
                        new
                        {
                            CategoryID = 2,
                            Name = "Habis Pakai"
                        });
                });

            modelBuilder.Entity("ManLab.Models.Tool", b =>
                {
                    b.Property<int>("ToolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ToolID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Tools");

                    b.HasData(
                        new
                        {
                            ToolID = 1,
                            CategoryID = 1,
                            Name = "Kursi"
                        },
                        new
                        {
                            ToolID = 2,
                            CategoryID = 1,
                            Name = "Meja"
                        },
                        new
                        {
                            ToolID = 3,
                            CategoryID = 2,
                            Name = "Spidol"
                        },
                        new
                        {
                            ToolID = 4,
                            CategoryID = 1,
                            Name = "Penghapus"
                        });
                });

            modelBuilder.Entity("ManLab.Models.Tool", b =>
                {
                    b.HasOne("ManLab.Models.Category", "Category")
                        .WithMany("Tools")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
