// <auto-generated />
using ManLab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ManLab.Migrations
{
    [DbContext(typeof(ManLabDataContext))]
    partial class ManLabDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ManLab.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Name = "Tetap"
                        },
                        new
                        {
                            CategoryID = 2,
                            Name = "Habis Pakai"
                        });
                });

            modelBuilder.Entity("ManLab.Models.Collection", b =>
                {
                    b.Property<int>("CollectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<int>("ToolID")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("CollectionID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("RoomID");

                    b.HasIndex("ToolID");

                    b.ToTable("Collections");

                    b.HasData(
                        new
                        {
                            CollectionID = 1,
                            CategoryID = 1,
                            RoomID = 1,
                            ToolID = 1,
                            Total = 10
                        },
                        new
                        {
                            CollectionID = 2,
                            CategoryID = 2,
                            RoomID = 2,
                            ToolID = 2,
                            Total = 20
                        },
                        new
                        {
                            CollectionID = 3,
                            CategoryID = 1,
                            RoomID = 3,
                            ToolID = 3,
                            Total = 30
                        },
                        new
                        {
                            CollectionID = 4,
                            CategoryID = 2,
                            RoomID = 4,
                            ToolID = 4,
                            Total = 40
                        },
                        new
                        {
                            CollectionID = 5,
                            CategoryID = 1,
                            RoomID = 1,
                            ToolID = 2,
                            Total = 50
                        });
                });

            modelBuilder.Entity("ManLab.Models.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomID = 1,
                            Name = "R01"
                        },
                        new
                        {
                            RoomID = 2,
                            Name = "R02"
                        },
                        new
                        {
                            RoomID = 3,
                            Name = "R03"
                        },
                        new
                        {
                            RoomID = 4,
                            Name = "R04"
                        });
                });

            modelBuilder.Entity("ManLab.Models.Tool", b =>
                {
                    b.Property<int>("ToolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ToolID");

                    b.ToTable("Tools");

                    b.HasData(
                        new
                        {
                            ToolID = 1,
                            Name = "Kursi"
                        },
                        new
                        {
                            ToolID = 2,
                            Name = "Meja"
                        },
                        new
                        {
                            ToolID = 3,
                            Name = "Spidol"
                        },
                        new
                        {
                            ToolID = 4,
                            Name = "Penghapus"
                        });
                });

            modelBuilder.Entity("ManLab.Models.Collection", b =>
                {
                    b.HasOne("ManLab.Models.Category", "Category")
                        .WithMany("Collections")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManLab.Models.Room", "Room")
                        .WithMany("Collections")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManLab.Models.Tool", "Tool")
                        .WithMany("Collections")
                        .HasForeignKey("ToolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
